export const navbarData = [
    {routeLink: 'home',
    icon: 'fa fa-home',
    label: 'Home',
},
{routeLink: 'about',
icon: 'fa fa-users',
label: 'About',
},
{routeLink: 'products',
icon: 'fa fa-shopping-cart',
label: 'Products',
},
{routeLink: 'standings',
icon: 'fa fa-chart-bar',
label: 'Standings',
},
{routeLink: 'media',
icon: 'fa fa-camera',
label: 'Media',
},
{routeLink: 'achievements',
icon: 'fa fa-trophy',
label: 'Achievements',
},

];